CREATE TABLE Products (
    id UUID PRIMARY KEY,
    productName TEXT,
    price INT,
    description TEXT,
    quantityInStock INT,
    category TEXT,
    brand TEXT,
    color TEXT,
    size TEXT,
    material TEXT,
    gender TEXT,
    discountPrice INT,
    isNewArrival BOOLEAN,
    isFeatured BOOLEAN,
    isBestSeller BOOLEAN,
    tags TEXT,
    images TEXT,
    isAvailable BOOLEAN
);
